### ISSUE TITLE
Saxon is not blocking unparsed-text and unparsed-text-available...

### ISSUE THREAD

**Issue by RackerWilliams** [rackerlabs/attributeMapping#38]
Saxon XPath parser when running in version 2.0 should not allow the functions ``unparsed-text`` and  ``unparsed-text-available``.  Not valid in XPath 2.0 should be valid in later versions of XPath and  under XSLT.  None the less, a quick check shows that they work -- even as we're running through the XPath 2.0 parser...

````yaml
---
mapping:
  rules:
    - remote:
      - path: |
         unparsed-text("/etc/passwd")
      local:
        user:
          domain: '78334'
          name: "{D}"
          email: "{D}"
          roles: "{0}"
          expire: "{D}"
  version: RAX-1
````
Damn it.

These two functions should be blocked along with ```doc``` and ```doc-available```.  

For the case of extreme safety should also block ```document``` function.  It's currently blocked...but you never know.

Also noticed that there is a whole lot of functions that are enabled if you have a SaxonEE license and some of them are not safe so block anything not in the standard namespace (fn) or in our own extension namespace.
